### ISSUE TITLE
Top google hit for Filecoin Foundation board gives error

### ISSUE THREAD

**Issue by dannyob** [FilecoinFoundationWeb/filecoin-foundation-site#68]
A concerned correspondent to me writes:
>  1) do a google search on “Filecoin Foundation Board.” Go to the first link, https://fil.org/board/.  And what’s returned is “ipfs resolve -r /ipfs/bafybeiexqfcqepp2e5wiaoozls7bg6ejovvz3tseex747pkuzwjxs44phm/board/: no link named “board” under bafybeiexqfcqepp2e5wiaoozls7bg6ejovvz3tseex747pkuzwjxs44phm”

I think this will eventually resolve on its own, but in the meantime could we put in a redirect at /board and perhaps some of the other maon URLs from the old site?

**Comment by orvn** [comment]
@dannyob thanks for reporting this. We just discussed this on Friday and a solution is in progress!

Because the site is on IPFS, there's no native way to handle redirects yet. Although it appears that a [solution is being worked on](https://github.com/ipfs/go-ipfs/issues/7392) that's similar to [Netlify's redriects](https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/).

For this reason we're building redirects into the routing for this app, and treating this as a high-priority issue.

**Comment by orvn** [comment]
Redirected all legacy paths found in the [previous site](https://github.com/FilecoinFoundationWeb/filecoin-foundation-site/tree/74d14efbc331a5013e8c464948a92f2453796945).

These are client side redirects, so it isn't perfect, but we'll implement redirects per IPFS' new implementation once it's available.

### List of redirected pages

- ~~About~~
- [Blog](https://fil.org/blog)
- [Board](https://fil.org/board)
- [Careers](https://fil.org/careers)
- [Community](https://fil.org/community)
- [Contact](https://fil.org/contact)
- [FilPlus](https://fil.org/filplus)
- [FIPs](https://fil.org/fips)
- [Philosophy](https://fil.org/philosophy)
- ~~Policy~~
- [Team](https://fil.org/team)
- ~~Terms~~

> \* Paths with ~~strikethrough~~ did not require a redirect because we use that same route in the new site
